services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jp_syllabaries_training_backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend/kana_training
      dockerfile: Dockerfile
    container_name: jp_syllabaries_training_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8000
    depends_on:
      - backend
